<h1 class="offset4">Job Listings</h1>
<br/>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <td>#</td>
            <td>Title</td>
            <td>Status</td>
            <td>Industry</td>
            <td>Category</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->jobListings as $key => $jobListing) { ?>
            <tr id="<?php echo $jobListing['id']; ?>">
                <td><?php echo $key + 1; ?></td>
                <td><?php ($jobListing['title']) ? $title = $jobListing['title'] : $title = '&nbsp;'; ?>
                    <a href="<?php echo $this->baseUrl('/job-listing/view?j=' . $jobListing['id']); ?>"><?php echo $title; ?></a>
                </td>
                <td><?php
        ($jobListing['jobListingStatus']->getName()) ? $status = $jobListing['jobListingStatus']->getName() : $status = '&nbsp;';
        echo $status;
            ?></td>
                <td><?php
                ($jobListing['industry']->getName()) ? $industry = $jobListing['industry']->getName() : $industry = '&nbsp;';
                echo $industry;
            ?></td>
                <td><?php
                ($jobListing['category']->getName()) ? $category = $jobListing['category']->getName() : $category = '&nbsp;';
                echo $category;
            ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>